spring:
  application:
    name: dishdash

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      timeout: 2000ms

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  jwt:
    expiration-ms: 86400000  # 24 hours

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs