ALTER TABLE customers ADD COLUMN IF NOT EXISTS created_by BIGINT,ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE delivery_addresses ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE menu_categories ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE combo_meals ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;